// Status values: "none" | "merged" | "pr" | "in-progress"
const COMPONENT_NODES = [
  { data: { id: "PDSAssetList",       label: "AssetList",       depth: 2, status: "merged" } },
  { data: { id: "PDSAssetTag",        label: "AssetTag",        depth: 0, status: "merged" } },
  { data: { id: "PDSBox",             label: "Box",             depth: 0, status: "merged" } },
  { data: { id: "PDSBreadCrumbs",     label: "BreadCrumbs",     depth: 2, status: "merged" } },
  { data: { id: "PDSButton",          label: "Button",          depth: 2, status: "merged" } },
  { data: { id: "PDSCard",            label: "Card",            depth: 1, status: "merged" } },
  { data: { id: "PDSCardHeader",      label: "CardHeader",      depth: 1, status: "merged" } },
  { data: { id: "PDSCarousel",        label: "Carousel",        depth: 3, status: "merged" } },
  { data: { id: "PDSComparisonTable", label: "ComparisonTable", depth: 2, status: "merged" } },
  { data: { id: "PDSControlGroup",    label: "ControlGroup",    depth: 1, status: "merged" } },
  { data: { id: "PDSDropdown",        label: "Dropdown",        depth: 2, status: "merged" } },
  { data: { id: "PDSFlexBox",         label: "FlexBox",         depth: 1, status: "merged" } },
  { data: { id: "PDSHeader",          label: "Header",          depth: 0, status: "merged" } },
  { data: { id: "PDSIcon",            label: "Icon",            depth: 1, status: "merged" } },
  { data: { id: "PDSIconButton",      label: "IconButton",      depth: 2, status: "merged" } },
  { data: { id: "PDSLayoutLoader",    label: "LayoutLoader",    depth: 0, status: "merged" } },
  { data: { id: "PDSLink",            label: "Link",            depth: 1, status: "merged" } },
  { data: { id: "PDSLinkWrapper",     label: "LinkWrapper",     depth: 0, status: "merged" } },
  { data: { id: "PDSNavBar",          label: "NavBar",          depth: 2, status: "merged" } },
  { data: { id: "PDSPageContentArea", label: "PageContentArea", depth: 0, status: "merged" } },
  { data: { id: "PDSPagination",      label: "Pagination",      depth: 3, status: "merged" } },
  { data: { id: "PDSSearchBar",       label: "SearchBar",       depth: 3, status: "merged" } },
  { data: { id: "PDSSeparator",       label: "Separator",       depth: 0, status: "merged" } },
  { data: { id: "PDSSubCard",         label: "SubCard",         depth: 0, status: "merged" } },
  { data: { id: "PDSSwitch",          label: "Switch",          depth: 1, status: "merged" } },
  { data: { id: "PDSTag",             label: "Tag",             depth: 2, status: "merged" } },
  { data: { id: "PDSText",            label: "Text",            depth: 0, status: "merged" } },
  { data: { id: "PDSTextInput",       label: "TextInput",       depth: 2, status: "merged" } },
  { data: { id: "PDSTooltip",         label: "Tooltip",         depth: 1, status: "merged" } },
  { data: { id: "PDSValueTag",        label: "ValueTag",        depth: 2, status: "merged" } },
];

const COMPONENT_EDGES = [
  { data: { source: "PDSAssetList",       target: "PDSAssetTag",    id: "PDSAssetList__PDSAssetTag" } },
  { data: { source: "PDSAssetList",       target: "PDSBox",         id: "PDSAssetList__PDSBox" } },
  { data: { source: "PDSAssetList",       target: "PDSFlexBox",     id: "PDSAssetList__PDSFlexBox" } },
  { data: { source: "PDSAssetList",       target: "PDSText",        id: "PDSAssetList__PDSText" } },
  { data: { source: "PDSBreadCrumbs",     target: "PDSFlexBox",     id: "PDSBreadCrumbs__PDSFlexBox" } },
  { data: { source: "PDSBreadCrumbs",     target: "PDSIcon",        id: "PDSBreadCrumbs__PDSIcon" } },
  { data: { source: "PDSBreadCrumbs",     target: "PDSText",        id: "PDSBreadCrumbs__PDSText" } },
  { data: { source: "PDSButton",          target: "PDSIcon",        id: "PDSButton__PDSIcon" } },
  { data: { source: "PDSButton",          target: "PDSText",        id: "PDSButton__PDSText" } },
  { data: { source: "PDSCard",            target: "PDSBox",         id: "PDSCard__PDSBox" } },
  { data: { source: "PDSCardHeader",      target: "PDSBox",         id: "PDSCardHeader__PDSBox" } },
  { data: { source: "PDSCardHeader",      target: "PDSSeparator",   id: "PDSCardHeader__PDSSeparator" } },
  { data: { source: "PDSCarousel",        target: "PDSBox",         id: "PDSCarousel__PDSBox" } },
  { data: { source: "PDSCarousel",        target: "PDSButton",      id: "PDSCarousel__PDSButton" } },
  { data: { source: "PDSCarousel",        target: "PDSFlexBox",     id: "PDSCarousel__PDSFlexBox" } },
  { data: { source: "PDSCarousel",        target: "PDSSeparator",   id: "PDSCarousel__PDSSeparator" } },
  { data: { source: "PDSComparisonTable", target: "PDSFlexBox",     id: "PDSComparisonTable__PDSFlexBox" } },
  { data: { source: "PDSControlGroup",    target: "PDSText",        id: "PDSControlGroup__PDSText" } },
  { data: { source: "PDSDropdown",        target: "PDSIcon",        id: "PDSDropdown__PDSIcon" } },
  { data: { source: "PDSDropdown",        target: "PDSText",        id: "PDSDropdown__PDSText" } },
  { data: { source: "PDSDropdown",        target: "PDSTooltip",     id: "PDSDropdown__PDSTooltip" } },
  { data: { source: "PDSFlexBox",         target: "PDSBox",         id: "PDSFlexBox__PDSBox" } },
  { data: { source: "PDSIcon",            target: "PDSBox",         id: "PDSIcon__PDSBox" } },
  { data: { source: "PDSIconButton",      target: "PDSIcon",        id: "PDSIconButton__PDSIcon" } },
  { data: { source: "PDSLink",            target: "PDSText",        id: "PDSLink__PDSText" } },
  { data: { source: "PDSNavBar",          target: "PDSFlexBox",     id: "PDSNavBar__PDSFlexBox" } },
  { data: { source: "PDSPagination",      target: "PDSFlexBox",     id: "PDSPagination__PDSFlexBox" } },
  { data: { source: "PDSPagination",      target: "PDSIconButton",  id: "PDSPagination__PDSIconButton" } },
  { data: { source: "PDSSearchBar",       target: "PDSIcon",        id: "PDSSearchBar__PDSIcon" } },
  { data: { source: "PDSSearchBar",       target: "PDSIconButton",  id: "PDSSearchBar__PDSIconButton" } },
  { data: { source: "PDSSwitch",          target: "PDSText",        id: "PDSSwitch__PDSText" } },
  { data: { source: "PDSTag",             target: "PDSIcon",        id: "PDSTag__PDSIcon" } },
  { data: { source: "PDSTextInput",       target: "PDSIcon",        id: "PDSTextInput__PDSIcon" } },
  { data: { source: "PDSTextInput",       target: "PDSText",        id: "PDSTextInput__PDSText" } },
  { data: { source: "PDSTextInput",       target: "PDSTooltip",     id: "PDSTextInput__PDSTooltip" } },
  { data: { source: "PDSTooltip",         target: "PDSBox",         id: "PDSTooltip__PDSBox" } },
  { data: { source: "PDSTooltip",         target: "PDSText",        id: "PDSTooltip__PDSText" } },
  { data: { source: "PDSValueTag",        target: "PDSIcon",        id: "PDSValueTag__PDSIcon" } },
];
